version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - recipe_uploads:/app/public/uploads
      - recipe_db:/app/prisma
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/prisma/dev.db

volumes:
  recipe_uploads:
  recipe_db: